export const adsWithFavorite = [
  {
    title: "Продам велосипед",
    description: "Горный велосипед в отличном состоянии.",
    img: "https://picsum.photos/seed/bike/400/300",
    cost: 12000,
    isFavorite: true,
  },
  {
    title: "Котята в добрые руки",
    description: "Игривые котята ищут дом. Бесплатно.",
    img: "https://picsum.photos/seed/kittens/400/300",
    cost: null,
    isFavorite: false,
  },
  {
    title: "Диван б/у",
    description: "Мягкий и удобный диван, слегка потертый.",
    img: "https://picsum.photos/seed/sofa/400/300",
    cost: 5000,
    isFavorite: true,
  },
  {
    title: "Курсы английского языка",
    description: "Интенсивные курсы английского для всех уровней.",
    img: "https://picsum.photos/seed/english/400/300",
    cost: 15000,
    isFavorite: false,
  },
  {
    title: "Продам гитару",
    description: "Акустическая гитара Yamaha, почти новая.",
    img: "https://picsum.photos/seed/guitar/400/300",
    cost: 8000,
    isFavorite: true,
  },
  {
    title: "Услуги электрика",
    description: "Быстрая и качественная помощь по дому.",
    img: "https://picsum.photos/seed/electric/400/300",
    cost: 3000,
    isFavorite: false,
  },
  {
    title: "Детская коляска",
    description: "Прочная и удобная коляска, подходит для прогулок.",
    img: "https://picsum.photos/seed/stroller/400/300",
    cost: 7000,
    isFavorite: true,
  },
  {
    title: "Отдам старую мебель",
    description: "Стол и шкаф в удовлетворительном состоянии, бесплатно.",
    img: "https://picsum.photos/seed/furniture/400/300",
    cost: null,
    isFavorite: false,
  },
  {
    title: "Аренда квартиры",
    description: "Однокомнатная квартира в центре города.",
    img: "https://picsum.photos/seed/apartment/400/300",
    cost: 25000,
    isFavorite: true,
  },
  {
    title: "Репетитор по математике",
    description: "Помогу школьникам и студентам.",
    img: "https://picsum.photos/seed/math/400/300",
    cost: 1000,
    isFavorite: false,
  },
  {
    title: "Продам швейную машинку",
    description: "Практически новая, полный комплект.",
    img: "https://picsum.photos/seed/sewing/400/300",
    cost: 9000,
    isFavorite: true,
  },
  {
    title: "Щенки в дар",
    description: "Очаровательные щенки ищут заботливых хозяев.",
    img: "https://picsum.photos/seed/puppies/400/300",
    cost: null,
    isFavorite: false,
  },
  {
    title: "Мастер на час",
    description: "Ремонтные работы любой сложности.",
    img: "https://picsum.photos/seed/handyman/400/300",
    cost: 2000,
    isFavorite: true,
  },
  {
    title: "Продам ноутбук",
    description: "Мощный ноутбук для работы и игр.",
    img: "https://picsum.photos/seed/laptop/400/300",
    cost: 55000,
    isFavorite: false,
  },
];

export const adsWithoutFavorite = adsWithFavorite.map((rest) => ({
  ...rest,
  isFavorite: undefined,
}));
