name: Deploy Frontend to Yandex Object Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Install pip
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install AWS CLI via pip
        run: pip3 install --upgrade --user awscli

      - name: Add AWS CLI to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Remove old frontend files from Yandex Object Storage (AWS CLI)
        run: |
          aws s3 rm s3://${{ secrets.YANDEX_S3_BUCKET }}/ --recursive \
          --exclude "admin/*" \
          --exclude "advertisements/*" \
          --exclude "drf-yasg/*" \
          --exclude "rest_framework/*" \
          --endpoint-url=https://storage.yandexcloud.net
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ru-central1

      - name: Sync dist to Yandex Object Storage (AWS CLI)
        run: |
          aws s3 sync dist/ s3://${{ secrets.YANDEX_S3_BUCKET }}/ --acl public-read --endpoint-url=https://storage.yandexcloud.net
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_S3_SECRET_KEY }}
